name: Frontend Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Configure Git
        run: |
          git config --global credential.helper store
          echo "https://${{ secrets.NETGAZE_TOKEN }}@github.com" > ~/.git-credentials
      
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.NETGAZE_TOKEN }}
      
      - name: Copy files and deploy
        run: |
          cp -r ./* /Users/admin/NetGaze360/frontend/
          cd /Users/admin/NetGaze360/frontend
          export PATH="$PATH:/Applications/Docker.app/Contents/Resources/bin"
          docker compose build ng360-frontend
          docker compose up -d --no-deps ng360-frontend

      - name: Clean up old images
        run: |
          docker image prune -f
